-- lab 5

CREATE TABLE HOSPITAL (
    ID INT NOT NULL,
    HOSPITAL_NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    HOSPITAL_PHONE VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PATIENT (
    ID INT NOT NULL,
    PATIENT_NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    EMERG_CONTACT VARCHAR(255) NOT NULL,
    PATIENT_PHONE VARCHAR(255) NOT NULL,
    HOSPITAL_ID INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_PATIENT_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(ID)
);

INSERT INTO HOSPITAL VALUES(11,'Super Good Hospital','999 Speedy Recover, ATL, GA, 99999','123-222-3333');
INSERT INTO HOSPITAL VALUES(22,'Happy Hospital','452 Journey Road, ATL, GA, 13453','881-222-4444');
INSERT INTO HOSPITAL VALUES(33,'Dangerous Hospital','321 No Recovery Rd, ATL, GA, 54545','909-222-7776');
INSERT INTO HOSPITAL VALUES(44,'Candy Land Hospital','902 Dancing Rd, ATL, GA, 22222','111-222-5399');
INSERT INTO HOSPITAL VALUES(55,'The New Hospital','467 McDonald Rd, ATL, GA, 86342','377-222-2443');

SELECT * FROM HOSPITAL;

INSERT INTO PATIENT VALUES (37442,'Billy Jeans','1111 Somewhere Here, ATL, GA, 11111','Jimmy John','404-888-8888',11);
INSERT INTO PATIENT VALUES (12345,'Didier Droga','1114 Nowhere, ATL, GA, 4','Paul Sheep','303-888-8888',22);
INSERT INTO PATIENT VALUES (54321,'Kai Havertz','2222 Backyard Here, ATL, GA, 22222','Rachel Lamb','555-888-8888',33);
INSERT INTO PATIENT VALUES (56666,'Mykhailo Mudryk','4511 Blahblah Lane, ATL, GA, 21111','Ester Baker','404-888-8887',22);
INSERT INTO PATIENT VALUES (78988,'Sally Brown','6111 NeverLand Rd, ATL, GA, 11112','Tommi Drew','404-868-8888',11);

SELECT * FROM PATIENT;

CREATE TABLE SPECIALTY (
    ID INT NOT NULL,
    SPECIALTY_TYPE VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO SPECIALTY VALUES (1,'brain');
INSERT INTO SPECIALTY VALUES (2,'general');
INSERT INTO SPECIALTY VALUES (3,'surgery');
INSERT INTO SPECIALTY VALUES (4,'covid');
INSERT INTO SPECIALTY VALUES (5,'bodily injured');

SELECT * FROM SPECIALTY;

CREATE TABLE HOSPITAL_SPECIALTY (
    ID INT NOT NULL PRIMARY KEY,
    HOSPITAL_ID INT NOT NULL,
    SPECIALTY_ID INT NOT NULL
);

INSERT INTO HOSPITAL_SPECIALTY VALUES (111,11,1);
INSERT INTO HOSPITAL_SPECIALTY VALUES (112,22,2);
INSERT INTO HOSPITAL_SPECIALTY VALUES (113,33,3);
INSERT INTO HOSPITAL_SPECIALTY VALUES (114,44,4);
INSERT INTO HOSPITAL_SPECIALTY VALUES (115,55,5);


ALTER TABLE HOSPITAL_SPECIALTY ADD CONSTRAINT FK_HOSSPECIALTY_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(ID);
ALTER TABLE HOSPITAL_SPECIALTY ADD CONSTRAINT FK_HOSSPECIALTY_SPECIALTY FOREIGN KEY (SPECIALTY_ID) REFERENCES SPECIALTY(ID);

SELECT * FROM HOSPITAL_SPECIALTY;

SELECT P.PATIENT_NAME, H.HOSPITAL_NAME FROM PATIENT P INNER JOIN HOSPITAL H ON P.HOSPITAL_ID = H.ID;

SELECT H.HOSPITAL_NAME, S.SPECIALTY_TYPE 
FROM HOSPITAL H 
    INNER JOIN HOSPITAL_SPECIALTY HS ON H.ID = HS.HOSPITAL_ID 
    INNER JOIN SPECIALTY S ON HS.SPECIALTY_ID = S.ID;

SELECT P.PATIENT_NAME FROM PATIENT P ORDER BY PATIENT_NAME DESC;


